# ================================================================
# Scripter Configuration
# ================================================================

[main]
parser_json = "build/parser/<profile>/parser_output.json"
default_template = "template.script"

[global]
regex = []

[ch-tools-changingowner]
template = "host-nosrc.script"

[ch-tools-creatingdirs]
template = "chroot-nosrc.script"

[ch-tools-createfiles]
template = "chroot-nosrc.script"
regex = [ "r@.*tester.*@@" ]

[ch-tools-cleanup]
template = "chroot-nosrc.script"


# Chapter-specific filters
# Example:
# [<chapter>]
# template = "chapter.script"
# regex = ["s/foo/bar/"]

# Section-specific filters
# Example:
# [<section>]
# template = "section.script"
# regex = []

# Package-specific filters
# Example:
# [<package>]
# template = "package.script"
# regex = []

