# ================================================================
# Parser Configuration
# ================================================================

[main]
xml_path = "build/books/${book}/lfs-full.xml"
output_file = "parser_output.json"

[xpaths]
source_book = ""
chapter_id = "//chapter"
section_id = "./sect1"
package_name = "./sect1info/productname/text()"
package_version = "./sect1info/productnumber/text()"
source_titles = ""
source_urls = "//sect1[@id='ch-materials-packages']//ulink[contains(@url,'${package_name}-${package_version}') and contains(@url,'.tar')]/@url"
source_checksums = ".//listitem//literal/text()"
dependencies = ""
build_instructions = ".//screen[not(@role=\"nodump\")]/userinput"


#------------------------------------------------------------------#
# XPATH overrides
#------------------------------------------------------------------#

[ch-tools-creatingminlayout.xpaths]
source_urls = ""

[ch-preps-addinguser.xpaths]
source_urls = ""

[ch-preps-settingenviron.xpaths]
source_urls = ""


#------------------------------------------------------------------#
# FILTERS
#------------------------------------------------------------------#

[chapter_filters]
include  = [ "chapter-final-preps" ]
exclude  = []

[section_filters]
include  = []
exclude  = [ "ch-preps-introduction", "ch-preps-aboutsbus", "ch-preps-abouttestsuites" ]

[package_filters]
include = []
exclude = []
deps    = []

