[scripter_aliases]
glib2 = "glib"
docbook = "docbook-xml"
docbook-xsl = "docbook-xsl-nons"
xorg-env = "xorg build environment"
xorg7-lib = "xorg libraries"
freetype2 = "freetype"
rust = "rustc"
pygobject3 = "pygobject"

[depsolver_aliases]
glib2 = "glib"
docbook = "docbook-xml-4.5"
docbook-xsl = "docbook-xsl-nons"
xorg-env = "xorg_build_environment"
xorg7-lib = "xorg_libraries"
freetype2 = "freetype"
rust = "rustc"
pygobject3 = "pygobject"