# ================================================================
# Scripter Configuration
# ================================================================

[main]
parser_json = "build/parser/<profile>/parser_output.json"
default_template = "template.script"

[global]
regex = []

[ch-materials-introduction]
template = "ch-materials-introduction.script"
regex = [ 
		"r@(?s)wget --input-file.*?.*\\$LFS/sources/\\*\\n?@@",
		"s@mkdir@sudo mkdir@",	
		"s@chmod@sudo chmod@",	
 ]

[chapter-getting-materials]
template = "chapter-getting-materials.script"


# Chapter-specific filters
# Example:
# [<chapter>]
# template = "chapter.script"
# regex = ["s/foo/bar/"]

# Section-specific filters
# Example:
# [<section>]
# template = "section.script"
# regex = []

# Package-specific filters
# Example:
# [<package>]
# template = "package.script"
# regex = []

