# ================================================================
# Scripter Configuration
# ================================================================

[main]
parser_json = "build/parser/${profile}/parser_output.json"
default_template = "template.script"

[global]
regex = []

[basedirs]
regex = [ "s@$LFS@$DESTDIR",
          "r@(cat >) (/.*)@\\1 $DESTDIR\\2@",
          "r@(echo .* >) (/.*)@\\1 $DESTDIR\\2@",
          "r@(ln)(.*) (/.*)@\\1\\2 $DESTDIR\\3@",
          "r@.*tester.*@@",
          "r@(touch) (/.*)@\\1 $DESTDIR\\2@",
          "r@(chgrp)(.*) (/.*)@\\1\\2 $DESTDIR\\3@",
          "r@(chmod)(.*) (/.*)@\\1\\2 $DESTDIR\\3@",
          "r@(?s)patch -Np1 -i.*?rm -v a.out\\n?@@",
          "r@(touch \\$DESTDIR/var/log/.*)@mkdir -p $DESTDIR/var/log\\n\\1@"
]

# Chapter-specific filters
# Example:
# [<chapter>]
# template = "chapter.script"
# regex = ["s/foo/bar/"]

# Section-specific filters
# Example:
# [<section>]
# template = "section.script"
# regex = []

# Package-specific filters
# Example:
# [<package>]
# template = "package.script"
# regex = []

