# ================================================================
# Parser Configuration
# ================================================================

[main]
xml_path = "build/books/${book}/lfs-full.xml"
output_file = "parser_output.json"

[xpaths]
source_book = ""
chapter_id = "//chapter"
section_id = "./sect1"
package_name = "./sect1info/productname/text()"
package_version = "./sect1info/productnumber/text()"
source_titles = ""
source_urls = "//sect1[@id='ch-materials-packages']//ulink[contains(@url,'${package_name}-${package_version}') and contains(@url,'.tar')]/@url"
source_checksums = ""
dependencies = ""
build_instructions = ".//screen[not(@role=\"nodump\")]/userinput"


#------------------------------------------------------------------#
# XPATH overrides
#------------------------------------------------------------------#

[ch-system-lz4.xpaths]
source_urls = "//sect1[@id='ch-materials-packages']//ulink[contains(@url,'lz4') and contains(@url,'.tar')]/@url"

[ch-system-tcl.xpaths]
source_urls = "//sect1[@id='ch-materials-packages']//ulink[contains(@url,'${package_name}') and contains(@url,'src') and contains(@url,'.tar')]/@url"

[ch-system-expect.xpaths]
source_urls = "//sect1[@id='ch-materials-packages']//ulink[contains(@url,'${package_name}') and contains(@url,'.tar')]/@url"

[ch-system-xml-parser.xpaths]
source_urls = "//sect1[@id='ch-materials-packages']//ulink[contains(@url,'XML-Parser') and contains(@url,'.tar')]/@url"

[ch-system-libelf.xpaths]
source_urls = "//sect1[@id='ch-materials-packages']//ulink[contains(@url,'elfutils') and contains(@url,'.tar')]/@url"

[ch-system-flit-core.xpaths]
source_urls = "//sect1[@id='ch-materials-packages']//ulink[contains(@url,'flit_core') and contains(@url,'.tar')]/@url"
[ch-system-stripping.xpaths]
source_urls = ""

[ch-system-cleanup.xpaths]
source_urls = ""


#------------------------------------------------------------------#
# FILTERS
#------------------------------------------------------------------#

[chapter_filters]
include  = [ "chapter-building-system" ]
exclude  = []

[section_filters]
include  = []
exclude  = [ "ch-system-introduction", "ch-system-pkgmgt", "ch-system-aboutdebug" ]

[package_filters]
include = []
exclude = []
deps    = []

