# ================================================================
# Parser Configuration (fixed for lowercase IDs + clean versions)
# ================================================================

[main]
xml_path = "build/books/${book}/blfs-systemd-full.xml"
output_file = "parser_output.json"

[xpaths]
source_book = ""
chapter_id = "//chapter"
section_id = "./sect1 | ./sect1/sect2"

# Lowercase section id for package_name
package_name = "translate(@id, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz')"

# Package version = everything after the last dash in the title, else blank
package_version = "substring-after(title/text(), concat('-', substring-after(title/text(), '-')))"

source_urls = ""
source_checksums = ""

# Dependencies (lowercased so IDs match package_name)
dependencies_required    = "translate(.//para[@role='required']//xref[not(@role='nodep') and not(@role='runtime')]/@linkend, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz')"
dependencies_recommended = "translate(.//para[@role='recommended']//xref[not(@role='nodep') and not(@role='runtime')]/@linkend, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz')"
dependencies_optional    = "translate(.//para[@role='optional']//xref[not(@role='nodep') and not(@role='runtime')]/@linkend, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz')"
dependencies_runtime     = "translate(.//para[@role='required' or @role='recommended']//xref[@role='runtime']/@linkend, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz')"

build_instructions = ""

#------------------------------------------------------------------#
# FILTERS
#------------------------------------------------------------------#

[chapter_filters]
include  = []
exclude  = []

[section_filters]
include  = []
exclude  = []

[package_filters]
include = [ "systemd" ]
exclude = []
deps    = [ "required","recommended","runtime" ]
