# ================================================================
# Parser Configuration (fixed for lowercase IDs + versions + deps)
# ================================================================

[main]
xml_path = "build/books/${book}/blfs-systemd-full.xml"
output_file = "parser_output.json"

[xpaths]
source_book = ""
chapter_id = "//chapter"
section_id = "./sect1 | ./sect1/sect2"
package_name    = "translate(@id, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz')"
#package_version = "substring-after(title/text(),concat(@id, '-'))"
package_version = "substring-after(translate(title/text(),'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),concat(@id,'-'))"
source_urls = ""
source_checksums = ""

# Dependencies (lowercased properly, not split into chars)
dependencies_required    = ".//para[@role='required']//xref[not(@role='nodep') and not(@role='runtime')]/@linkend"
dependencies_recommended = ".//para[@role='recommended']//xref[not(@role='nodep') and not(@role='runtime')]/@linkend"
dependencies_optional    = ".//para[@role='optional']//xref[not(@role='nodep') and not(@role='runtime')]/@linkend"
dependencies_runtime     = ".//para[@role='required' or @role='recommended']//xref[@role='runtime']/@linkend"

build_instructions = ""

#[glib2.xpaths]
#package_version = "substring-after(translate(title/text(),'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),concat(@id,'-'))"

[docbook-xsl.xpaths]
package_version = "substring-after(substring-after(translate(title/text(),'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),concat(@id,'-')),'-')"

#------------------------------------------------------------------#
# FILTERS
#------------------------------------------------------------------#

[chapter_filters]
include  = []
exclude  = []

[section_filters]
include  = []
exclude  = []

[package_filters]
include = [ "systemd" ]
exclude = []
deps    = [ "required","recommended","runtime" ]
