# ================================================================
# Scripter Configuration
# ================================================================

[main]
parser_json = "build/parser/<profile>/parser_output.json"
default_template = "template.script"

[global]
regex = []

[chapter-final-preps]
template = "chapter-final-preps.script"
regex =	[
	    "s@groupadd lfs@getent group lfs >/dev/null || groupadd lfs@",
	    "r@(useradd.*)@id -u lfs >/dev/null 2>&1 || \\1@"
	]  

[ch-preps-settingenviron]
template = "ch-preps-settingenviron.script"
regex = [ "s@$(uname -m)@\\$(uname -m)@", 
	  "s@$PATH@\\$PATH@",
	  "s@$LFS/@\\$LFS/@",
	  "s@$(nproc)@\\$(nproc)@" 
	]


# Chapter-specific filters
# Example:
# [<chapter>]
# template = "chapter.script"
# regex = ["s/foo/bar/"]

# Section-specific filters
# Example:
# [<section>]
# template = "section.script"
# regex = []

# Package-specific filters
# Example:
# [<package>]
# template = "package.script"
# regex = []

